import port1 from './../assets/port1.jpeg'
import port2 from './../assets/port2.jpg'
import port3 from './../assets/port3.jpg'
import port4 from './../assets/port4.jpg'
const portfolios = [
    {
    id:1,
    category:"animation",
    title:"template1",
    image:port1,
    link1:"www.youtube.com",
    link2:"www.github.com",
    icon1:"G",
    icon2:"Y",
    },
    {
        id:2,
        category:"web",
        title:"template2",
        image:port2,
        link1:"www.youtube.com",
        link2:"www.github.com",
        icon1:"G",
        icon2:"Y",
        },
        {
            id:3,
            category:"desing",
            title:"template3",
            image:port3,
            link1:"www.youtube.com",
            link2:"www.github.com",
            icon1:"G",
            icon2:"Y",
            },
            {
                id:4,
                category:"animation",
                title:"template4",
                image:port4,
                link1:"www.youtube.com",
                link2:"www.github.com",
                icon1:"G",
                icon2:"Y",
                },
                {
                id:5,
                category:"mobile",
                title:"template5",
                image:port4,
                link1:"www.youtube.com",
                link2:"www.github.com",
                icon1:"G",
                icon2:"Y",
                },
                {
                    id:6,
                    category:"web",
                    title:"template6",
                    image:port4,
                    link1:"www.youtube.com",
                    link2:"www.github.com",
                    icon1:"G",
                    icon2:"Y",
                    },
                    {
                        id:7,
                        category:"mobile",
                        title:"template7",
                        image:port4,
                        link1:"www.youtube.com",
                        link2:"www.github.com",
                        icon1:"G",
                        icon2:"Y",
                        }
]
export default portfolios